[project]
name = "update-segment-functions"
version = "0.1.0"
description = ""
dependencies = [
    "pyyaml",
]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_backend"
